### ISSUE TITLE
Feature Request: Blender add-on

### ISSUE THREAD

**Issue by xan2622** [yuchen071/Normal-map-generator#6]
Hi.

Have you considered making an add-on for Blender?

There are many artists who would love to be able to import an image in Blender (let's say, a texture) and have an add-on that could generate for Diffuse, Normal, Displacement, Occlusion, Specular, Roughness maps.

Thank you in advance.

**Comment by xan2622** [comment]
That add-on would work perfectly alongside Dream-Textures: https://github.com/carson-katri/dream-textures (which doesn't generate such maps).

**Comment by yuchen071** [comment]
That's a whole different beast for me to tackle 😅
Probably won't ever be done by me. But anyone is welcome to fork it!
